//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.BillPayments = new HashSet<BillPayment>();
            this.BillTimeSheetDetails = new HashSet<BillTimeSheetDetail>();
        }
    
        public long Id { get; set; }
        public string BillNumber { get; set; }
        public Nullable<long> BillTypeId { get; set; }
        public long ProjectId { get; set; }
        public long EmployeeId { get; set; }
        public Nullable<long> VendorId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> BillReceivedDate { get; set; }
        public Nullable<double> WorkedHours { get; set; }
        public Nullable<decimal> VendorRate { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<System.DateTime> BillPaidDate { get; set; }
        public long StatusId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual LOVItemValue LOVItemValue { get; set; }
        public virtual LOVItemValue LOVItemValue1 { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillPayment> BillPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillTimeSheetDetail> BillTimeSheetDetails { get; set; }
    }
}
