//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFinanceDeal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeFinanceDeal()
        {
            this.EmployeeProjectRates = new HashSet<EmployeeProjectRate>();
        }
    
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public int FromHours { get; set; }
        public int ToHours { get; set; }
        public long TypeId { get; set; }
        public decimal DealValue { get; set; }
        public bool IsPercent { get; set; }
        public Nullable<decimal> AdditionalAmount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LOVItemValue LOVItemValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeProjectRate> EmployeeProjectRates { get; set; }
    }
}
