//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProjectRate
    {
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public long ProjectId { get; set; }
        public Nullable<long> DealId { get; set; }
        public int FromHours { get; set; }
        public int ToHours { get; set; }
        public decimal RatePerHour { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual EmployeeFinanceDeal EmployeeFinanceDeal { get; set; }
        public virtual Project Project { get; set; }
    }
}
