//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRoll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayRoll()
        {
            this.PayRollTimeSheetDetails = new HashSet<PayRollTimeSheetDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PayCycleId { get; set; }
        public long EmployeeId { get; set; }
        public decimal Basic { get; set; }
        public decimal HotSkillsSalary { get; set; }
        public decimal PerDiemPayment { get; set; }
        public decimal Deduction { get; set; }
        public decimal VariablePay { get; set; }
        public decimal Federal { get; set; }
        public decimal State { get; set; }
        public decimal Other { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public long StatusId { get; set; }
        public bool IsApproved { get; set; }
        public bool IsEdited { get; set; }
        public bool IsReconciled { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LOVItemValue LOVItemValue { get; set; }
        public virtual PayCycle PayCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRollTimeSheetDetail> PayRollTimeSheetDetails { get; set; }
    }
}
