//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionDetail
    {
        public long Id { get; set; }
        public Nullable<long> RequisitionId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<long> ItemTypeId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<long> CostCenterId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> SubAccountId { get; set; }
        public Nullable<long> StatusId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual LOVItemValue LOVItemValue { get; set; }
        public virtual LOVItemValue LOVItemValue1 { get; set; }
        public virtual LOVItemValue LOVItemValue2 { get; set; }
        public virtual LOVItemValue LOVItemValue3 { get; set; }
        public virtual LOVItemValue LOVItemValue4 { get; set; }
        public virtual LOVItemValue LOVItemValue5 { get; set; }
        public virtual Requisition Requisition { get; set; }
    }
}
