//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeQualificationDetail
    {
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public long QualificationId { get; set; }
        public Nullable<long> SpecializationId { get; set; }
        public Nullable<long> CampusId { get; set; }
        public string OtherCampus { get; set; }
        public int PassingYear { get; set; }
        public bool IsFullTime { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LOVItemValue LOVItemValue { get; set; }
        public virtual LOVItemValue LOVItemValue1 { get; set; }
        public virtual LOVItemValue LOVItemValue2 { get; set; }
    }
}
