//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Bills = new HashSet<Bill>();
            this.EmployeeAddresses = new HashSet<EmployeeAddress>();
            this.EmployeeDocumentDetails = new HashSet<EmployeeDocumentDetail>();
            this.EmployeeFinanceBenefits = new HashSet<EmployeeFinanceBenefit>();
            this.EmployeeFinanceDeals = new HashSet<EmployeeFinanceDeal>();
            this.EmployeeFromVendors = new HashSet<EmployeeFromVendor>();
            this.EmployeeProjectRates = new HashSet<EmployeeProjectRate>();
            this.EmployeeQualificationDetails = new HashSet<EmployeeQualificationDetail>();
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
            this.Invoices = new HashSet<Invoice>();
            this.Projects = new HashSet<Project>();
            this.RequisitionApprovals = new HashSet<RequisitionApproval>();
            this.TimeSheets = new HashSet<TimeSheet>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public long LegalStatusId { get; set; }
        public string SSN { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public Nullable<System.DateTime> VisaExpirationDate { get; set; }
        public double TotalExperience { get; set; }
        public long EmploymentTypeId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual LOVItemValue LOVItemValue { get; set; }
        public virtual LOVItemValue LOVItemValue1 { get; set; }
        public virtual ICollection<EmployeeAddress> EmployeeAddresses { get; set; }
        public virtual ICollection<EmployeeDocumentDetail> EmployeeDocumentDetails { get; set; }
        public virtual ICollection<EmployeeFinanceBenefit> EmployeeFinanceBenefits { get; set; }
        public virtual ICollection<EmployeeFinanceDeal> EmployeeFinanceDeals { get; set; }
        public virtual ICollection<EmployeeFromVendor> EmployeeFromVendors { get; set; }
        public virtual ICollection<EmployeeProjectRate> EmployeeProjectRates { get; set; }
        public virtual ICollection<EmployeeQualificationDetail> EmployeeQualificationDetails { get; set; }
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<RequisitionApproval> RequisitionApprovals { get; set; }
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
    }
}
