//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOVItemValue
    {
        public LOVItemValue()
        {
            this.Bills = new HashSet<Bill>();
            this.Bills1 = new HashSet<Bill>();
            this.Budgets = new HashSet<Budget>();
            this.Budgets1 = new HashSet<Budget>();
            this.Budgets2 = new HashSet<Budget>();
            this.Budgets3 = new HashSet<Budget>();
            this.Companies = new HashSet<Company>();
            this.Companies1 = new HashSet<Company>();
            this.CompanyContacts = new HashSet<CompanyContact>();
            this.Documents = new HashSet<Document>();
            this.Employees = new HashSet<Employee>();
            this.Employees1 = new HashSet<Employee>();
            this.EmployeeDocumentDetails = new HashSet<EmployeeDocumentDetail>();
            this.EmployeeFinanceBenefits = new HashSet<EmployeeFinanceBenefit>();
            this.EmployeeFinanceDeals = new HashSet<EmployeeFinanceDeal>();
            this.EmployeeQualificationDetails = new HashSet<EmployeeQualificationDetail>();
            this.EmployeeQualificationDetails1 = new HashSet<EmployeeQualificationDetail>();
            this.EmployeeQualificationDetails2 = new HashSet<EmployeeQualificationDetail>();
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
            this.Invoices = new HashSet<Invoice>();
            this.LOVItemValue1 = new HashSet<LOVItemValue>();
            this.MenuActivities = new HashSet<MenuActivity>();
            this.Payments = new HashSet<Payment>();
            this.Requisitions = new HashSet<Requisition>();
            this.Requisitions1 = new HashSet<Requisition>();
            this.RequisitionApprovals = new HashSet<RequisitionApproval>();
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
            this.RequisitionDetails1 = new HashSet<RequisitionDetail>();
            this.RequisitionDetails2 = new HashSet<RequisitionDetail>();
            this.RequisitionDetails3 = new HashSet<RequisitionDetail>();
            this.RequisitionDetails4 = new HashSet<RequisitionDetail>();
            this.RequisitionDetails5 = new HashSet<RequisitionDetail>();
            this.TimeSheets = new HashSet<TimeSheet>();
            this.TimeSheetEntries = new HashSet<TimeSheetEntry>();
        }
    
        public long Id { get; set; }
        public string ItemValue { get; set; }
        public long ItemId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<Bill> Bills1 { get; set; }
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<Budget> Budgets1 { get; set; }
        public virtual ICollection<Budget> Budgets2 { get; set; }
        public virtual ICollection<Budget> Budgets3 { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Company> Companies1 { get; set; }
        public virtual ICollection<CompanyContact> CompanyContacts { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Employee> Employees1 { get; set; }
        public virtual ICollection<EmployeeDocumentDetail> EmployeeDocumentDetails { get; set; }
        public virtual ICollection<EmployeeFinanceBenefit> EmployeeFinanceBenefits { get; set; }
        public virtual ICollection<EmployeeFinanceDeal> EmployeeFinanceDeals { get; set; }
        public virtual ICollection<EmployeeQualificationDetail> EmployeeQualificationDetails { get; set; }
        public virtual ICollection<EmployeeQualificationDetail> EmployeeQualificationDetails1 { get; set; }
        public virtual ICollection<EmployeeQualificationDetail> EmployeeQualificationDetails2 { get; set; }
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual LOVItem LOVItem { get; set; }
        public virtual ICollection<LOVItemValue> LOVItemValue1 { get; set; }
        public virtual LOVItemValue LOVItemValue2 { get; set; }
        public virtual ICollection<MenuActivity> MenuActivities { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Requisition> Requisitions { get; set; }
        public virtual ICollection<Requisition> Requisitions1 { get; set; }
        public virtual ICollection<RequisitionApproval> RequisitionApprovals { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails1 { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails2 { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails3 { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails4 { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails5 { get; set; }
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
        public virtual ICollection<TimeSheetEntry> TimeSheetEntries { get; set; }
    }
}
