//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.BillPayments = new HashSet<BillPayment>();
            this.BillPaymentDocuments = new HashSet<BillPaymentDocument>();
            this.InvoicePayments = new HashSet<InvoicePayment>();
            this.InvoicePaymentDocuments = new HashSet<InvoicePaymentDocument>();
        }
    
        public long Id { get; set; }
        public System.DateTime PayDate { get; set; }
        public decimal PayAmount { get; set; }
        public long PayMode { get; set; }
        public string PayDetails { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<BillPayment> BillPayments { get; set; }
        public virtual ICollection<BillPaymentDocument> BillPaymentDocuments { get; set; }
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        public virtual ICollection<InvoicePaymentDocument> InvoicePaymentDocuments { get; set; }
        public virtual LOVItemValue LOVItemValue { get; set; }
    }
}
