//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Bills = new HashSet<Bill>();
            this.EmployeeProjectRates = new HashSet<EmployeeProjectRate>();
            this.Invoices = new HashSet<Invoice>();
            this.ProjectDocuments = new HashSet<ProjectDocument>();
            this.ProjectLocations = new HashSet<ProjectLocation>();
            this.TimeSheets = new HashSet<TimeSheet>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> ClientId { get; set; }
        public string EndClient { get; set; }
        public Nullable<long> ContactPersonId { get; set; }
        public Nullable<long> ConsultantId { get; set; }
        public System.DateTime StartDate { get; set; }
        public short DurationInMonths { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal ClientRatePerHour { get; set; }
        public Nullable<decimal> VendorRatePerHour { get; set; }
        public Nullable<decimal> AdministrativeChargePerHour { get; set; }
        public Nullable<short> DurationInHours { get; set; }
        public bool IsProjectHoursRestricted { get; set; }
        public Nullable<byte> WeeklyDurationInHours { get; set; }
        public bool IsProjectWeeklyHoursRestristed { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Company Company { get; set; }
        public virtual CompanyContact CompanyContact { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<EmployeeProjectRate> EmployeeProjectRates { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<ProjectDocument> ProjectDocuments { get; set; }
        public virtual ICollection<ProjectLocation> ProjectLocations { get; set; }
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
    }
}
