//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSetting
    {
        public long Id { get; set; }
        public int CR_Grouped { get; set; }
        public decimal CR_Tolerance { get; set; }
        public int VT_MaxDiffInInvoceTerms { get; set; }
        public int VT_MaxDiffInPayTerms { get; set; }
        public int VT_UnAcceptDiffInvoiceterms { get; set; }
        public int VT_UnAcceptDiffPayTerms { get; set; }
        public decimal VT_InvoiceTermsBtMaxNUnAccept { get; set; }
        public decimal VT_PayTermsBtMaxNUnAccept { get; set; }
        public decimal VT_Invoice_Tolerance { get; set; }
        public decimal VT_Payterms_Tolerance { get; set; }
        public int CPT_MaxInvoiceTerms { get; set; }
        public int CPT_MaxPayTerms { get; set; }
        public int CPT_UnAcceptPayTerms { get; set; }
        public int CPT_PayTermsAboveMaxNbelowUnAccept { get; set; }
        public int CPT_Invoice_Tolerance_C2C { get; set; }
        public int CPT_Payterms_Tolerance_C2C { get; set; }
        public int CPT_Invoice_Tolerance_EMP { get; set; }
        public int CPT_Payterms_Tolerance_EMP { get; set; }
        public decimal WM_C2CMargin { get; set; }
        public decimal WM_EmployeeTolerance { get; set; }
        public int WM_Tolerance_Period { get; set; }
        public int WM_NoofHours { get; set; }
        public int WM_MinMargin { get; set; }
        public int WM_MaxMargin { get; set; }
        public decimal WM_Tolerance { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
