//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public Requisition()
        {
            this.RequisitionApprovals = new HashSet<RequisitionApproval>();
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
        }
    
        public long Id { get; set; }
        public System.DateTime RequisitionDate { get; set; }
        public string RequisitionBy { get; set; }
        public string Description { get; set; }
        public Nullable<long> RequisitionType { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<long> StatusId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual LOVItemValue LOVItemValue { get; set; }
        public virtual LOVItemValue LOVItemValue1 { get; set; }
        public virtual ICollection<RequisitionApproval> RequisitionApprovals { get; set; }
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
    }
}
