//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staffing.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<Bill> Bills { get; set; }
        public DbSet<BillPayment> BillPayments { get; set; }
        public DbSet<BillPaymentDocument> BillPaymentDocuments { get; set; }
        public DbSet<BillTimeSheetDetail> BillTimeSheetDetails { get; set; }
        public DbSet<Budget> Budgets { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyAddress> CompanyAddresses { get; set; }
        public DbSet<CompanyContact> CompanyContacts { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<EmployeeAddress> EmployeeAddresses { get; set; }
        public DbSet<EmployeeDocumentDetail> EmployeeDocumentDetails { get; set; }
        public DbSet<EmployeeFinanceBenefit> EmployeeFinanceBenefits { get; set; }
        public DbSet<EmployeeFinanceDeal> EmployeeFinanceDeals { get; set; }
        public DbSet<EmployeeFromVendor> EmployeeFromVendors { get; set; }
        public DbSet<EmployeeProjectRate> EmployeeProjectRates { get; set; }
        public DbSet<EmployeeQualificationDetail> EmployeeQualificationDetails { get; set; }
        public DbSet<EmployeeSalary> EmployeeSalaries { get; set; }
        public DbSet<EmployeeSkill> EmployeeSkills { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<InvoiceFollowUpDetail> InvoiceFollowUpDetails { get; set; }
        public DbSet<InvoicePayment> InvoicePayments { get; set; }
        public DbSet<InvoicePaymentDocument> InvoicePaymentDocuments { get; set; }
        public DbSet<LOVItem> LOVItems { get; set; }
        public DbSet<LOVItemValue> LOVItemValues { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<MenuActivity> MenuActivities { get; set; }
        public DbSet<MenuActivityPermission> MenuActivityPermissions { get; set; }
        public DbSet<PayCycle> PayCycles { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<PaymentSetting> PaymentSettings { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectDocument> ProjectDocuments { get; set; }
        public DbSet<ProjectLocation> ProjectLocations { get; set; }
        public DbSet<ProjectSetting> ProjectSettings { get; set; }
        public DbSet<Requisition> Requisitions { get; set; }
        public DbSet<RequisitionApproval> RequisitionApprovals { get; set; }
        public DbSet<RequisitionDetail> RequisitionDetails { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TimeSheet> TimeSheets { get; set; }
        public DbSet<TimeSheetAlert> TimeSheetAlerts { get; set; }
        public DbSet<TimeSheetDocument> TimeSheetDocuments { get; set; }
        public DbSet<TimeSheetEntry> TimeSheetEntries { get; set; }
    }
}
